### ISSUE TITLE
When graphqlgen large schema will get stuck

### ISSUE THREAD

**Issue by Victorkangsh** [prisma/graphqlgen#310]
## Description
In one of my projects, the datamodel has five hundred lines. My `schema.graphql` file imports the generated `prisma.graphql` schema file and has a hundred lines of Query and Mutation.

I get stuck when I run graphqlgen. Cpu and memory are slightly higher. I noticed a prompt for the `find prettier`, but I still didn't succeed after removing the prettier configuration.

My three computers have linux, mac, and windows systems, and they are not working properly. But the surprise is that my mac has been successful once, just once.

## Steps to reproduce
When `schema.graphql` too large.

My other small project run graphqlgen perfectly.

## Expected results
Graphqlgen work success.

## Actual results
Stucked. And console has no message.

## Versions
- graphqlgen: 0.4.0
- OS name and version: mac: 16G memory, mojava(darwin-x64). windows: win10 16G memory i7.
- Node: node-v10.8.0

**Comment by Victorkangsh** [comment]
Supplement： 
When wait 1 hour later, console log err as follows：
```bash
graphqlgen
<--- Last few GCs --->

[14832:000002002A721AF0]  8948164 ms: Mark-sweep 1159.4 (1202.0) -> 1159.4 (1165.5) MB, 3679.4 / 0.0 ms  last resort GC in old space requested
[14832:000002002A721AF0]  8948951 ms: Mark-sweep 1159.4 (1165.5) -> 1159.4 (1165.5) MB, 786.8 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000038B35425EE1 <JSObject>
    0: builtin exit frame: concat(this=000002C19A6AE511 <JSArray[40009211]>,000002C19A682201 <JSArray[18728217]>)

    1: flatten(aka flatten) [C:\Users\T47\AppData\Roaming\npm\node_modules\graphqlgen\dist\utils.js:~49] [pc=000002BC79E8D883](this=0000006577382311 <undefined>,a=000002C19A6AE511 <JSArray[40009211]>,b=000002C19A682201 <JSArray[18728217]>)
    2: arguments adaptor frame: 4->2
    ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by LawJolla** [comment]
Same issue.

**Comment by LawJolla** [comment]
@mentrie If That for the suggestion.  But if I downgrade, then I'm hit with the #280 bug 😢

**Comment by mentrie** [comment]
@LawJolla Right. For the past 1hr, `0.4.0` is still running 😢

**Comment by frankdugan3** [comment]
Same issue here. Can't use at all until this is resolved. My system has 32 GB of RAM, and it still doesn't work. Haven't let it run for an hour, but after several minutes I still have plenty of RAM left.

**Comment by woss** [comment]
I've spend few hours debugging the package and it seems that here : 
https://github.com/prisma/graphqlgen/blob/03336f01d1257643c4b24577a397df44bd00076a/packages/graphqlgen/src/generators/common.ts#L228 it turns into the endless loop.

When i add Mutation to my schema with the same name as one in the `prisma.graphql` it runs until it fails.

**Comment by woss** [comment]
> @mentrie Thanks for the suggestion. But if I downgrade, then I'm hit with the #280 bug 😢

that has been fixed. I've downgraded to `0.3.0` and it worked even with the schema that fails on `0.4.0`

**Comment by LawJolla** [comment]
> > @mentrie Thanks for the suggestion. But if I downgrade, then I'm hit with the #280 bug 😢
> 
> that has been fixed. I've downgraded to `0.3.0` and it worked even with the schema that fails on `0.4.0`

@woss It's still an issue for me in 0.3.0.  This project looked promising, but it now appears abandoned.  I've given up and gone back to Javascript to actually get things built... pesky deadlines. :)

**Comment by jasonkuhrt** [comment]
Anyone have a schema that leads to this issue that they can share?

**Comment by Victorkangsh** [comment]
@jasonkuhrt  I have figured out its problem, it has nothing to do with the size of the schema, but an error when using the imported Input Type.
like this example : https://github.com/prisma/graphql-prisma-typescript/blob/master/src/schema.graphql 

when you add some Mutation using imported Input Type it will stuck:
```graphql
# import * from "./generated/prisma.graphql"
type Mutation {
  addPaymentMethod(
    PaymentCreateInput
  ): MutationResult!
  book(
    BookingCreateInput
  ): MutationResult!
}
```

**Comment by vdiaz1130** [comment]
This bug renders graphqlgen unusable for me. Running with version 3 I get a bunch of TS errors while running on latest gets stuck. 

I was more specific with my imports from Prisma generated code.

    // I used
    # import Post, User, UserCreateInput, UserUpdateInput from './generated/prisma.graphql'

    // VS
    # import * from "./generated/prisma.graphql"

    node -v
    v11.4.0

    npm -v
    6.4.1

    OSx 10.12.6

    prisma -v
    prisma/1.22.2


https://ibb.co/0DjYqkG

Any hacky workaround ideas for now? A nightly I can test?

**Comment by vdiaz1130** [comment]
Quick update: in VS code, using `cmd + .` then selecting `add all missing imports` adds all missing imports - who would've thought?

**Comment by jasonkuhrt** [comment]
@Victorkangsh iiuc:

1. This issue occurs in conjunction with graphql import

2. I should be able to repro with 
https://github.com/prisma/graphql-prisma-typescript/blob/master/src/schema.graphql

3. But a more minimal repro can be had by importing one schema (A) into another (B) and using A types in B `Mutation` fields args.

Did I get that right?

**Comment by Victorkangsh** [comment]
@jasonkuhrt  I think the problem is nested InputType.
I use this config:
<img width="1115" alt="2018-12-20 3 22 41" src="https://user-images.githubusercontent.com/21174764/50270222-d7cc1a00-046b-11e9-8642-3bdee72c31ba.png">
<img width="714" alt="2018-12-20 3 22 53" src="https://user-images.githubusercontent.com/21174764/50270229-db5fa100-046b-11e9-9a54-2e8b88386ed7.png">

when I try this:
<img width="910" alt="2018-12-20 3 23 17" src="https://user-images.githubusercontent.com/21174764/50270242-e3b7dc00-046b-11e9-847d-fd3bc2cb5d5d.png">

it's not work, and i copy in schema:
<img width="827" alt="2018-12-20 3 25 00" src="https://user-images.githubusercontent.com/21174764/50270274-f7fbd900-046b-11e9-9c0d-531ec431ea6c.png">
still stuck.
But when I remove nest Type , it worked:
<img width="816" alt="2018-12-20 3 25 34" src="https://user-images.githubusercontent.com/21174764/50270349-3abdb100-046c-11e9-853d-07cb8b873e6d.png">

**Comment by Victorkangsh** [comment]
graphql import is no problem, I test this:
<img width="369" alt="2018-12-20 3 36 35" src="https://user-images.githubusercontent.com/21174764/50270654-43fb4d80-046d-11e9-9604-6da52861b8b3.png">
<img width="564" alt="2018-12-20 3 37 06" src="https://user-images.githubusercontent.com/21174764/50270658-465da780-046d-11e9-84af-33d8928aecc4.png">
all success

**Comment by vdiaz1130** [comment]
@jasonkuhrt 

> Anyone have a schema that leads to this issue that they can share?

https://github.com/vdiaz1130/graphqlgen-issue310

**Comment by psycura** [comment]
> Anyone have a schema that leads to this issue that they can share?

[](https://gist.github.com/psycura/acdf13991df107bf53e6fef40e23b2f7
)

**Comment by atardadi** [comment]
To provide some more context. 
I tried debugging it with console.logs, and I see that it gets stuck around getDistinctInputTypes method in common.js file.
I could see that the type it's trying to parse is Mutation

**Comment by vdiaz1130** [comment]
I worked around this by not importing from Prisma generated. I simply copied over my schema and removed all the Prisma specific things (@relation, @default, etc). Also using version 0.3.0 of graphqlgen.

If in your Prisma generated code you have an error on the Model interface, delete the import and reimported via VS code "cmd + ." It should import from a ''prisma-client-lib/dist/types' - Fix this before you generate with graphqlgen.

After generating with graphqlgen, If you get missing imports from your generated code and you are using VS Code, go next to a type, class, interface etc, then hit "cmd + ." Select "add all missing imports".

**Comment by LawJolla** [comment]
Thanks @jasonkuhrt !

Is there a particular release we should try?  I still see 0.4.0 as the current.

**Comment by atardadi** [comment]
> Before considering this issue resolved I'd like to hear from multiple users if its their experience that the issue is resolved too.

I added the line you added in the [pull request](https://github.com/prisma/graphqlgen/pull/373) to my local code.
It's been running for ~90 mins without stopping.
Looks like it's still reproducing.

**Comment by jasonkuhrt** [comment]
@LawJolla I'm not doing releases yet myself I'm afraid (might start to this or next month though) but maybe you could pull down from git repo (but build steps and all...). Given the diff is trivial what @atardadi did might be easiest.

@atardadi thanks for the feedback! Good to know...

**Comment by jasonkuhrt** [comment]
@vdiaz1130 thanks for the repo repro. I'd like to extract the minimal:

1. the model file(s)
2. the schema file(s)

I need and repro with the graphqlgen test suite.

But, can you advise how I should get `prisma-client-lib` installed and setup exactly? Even better might be a repro that doesn't need that dep to begin with (would simplify a bit I suppose).

**Comment by devautor** [comment]
I was so excited with graphqlgen :(
Even if there is a way around, there are a lot of issues unfixed!

**Comment by jasonkuhrt** [comment]
@Victorkangsh ok thanks for confirming, interesting... I think then, since this issue was originally created by you we should close it. Others have raised other issues here but going by your feedback, they are different issues. As such I would like to see them tracked as separate issues and have focused discussion.

Does anyone strongly object?

**Comment by atardadi** [comment]
> @Victorkangsh ok thanks for confirming, interesting... I think then, since this issue was originally created by you we should close it. Others have raised other issues here but going by your feedback, they are different issues. As such I would like to see them tracked as separate issues and have focused discussion.
> 
> Does anyone strongly object?

I don't mind, although I have the same issue - once my schema grew large it doesn't generate it for me.
We could try publishing a new version and see if that solves it for me. 
Otherwise, I will create a separate issue

**Comment by delianides** [comment]
@Victorkangsh was there a separate issue created for this?
